
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2025.7.2
    container_name: homeassistant
    hostname: homeassistant
    restart: unless-stopped
    volumes:
      - D:/home-automation/homeassistant:/config
    ports:
      - 8123:8123
    environment:
      - TZ=${TZ}
    privileged: true
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:2.5.1
    container_name: zigbee2mqtt
    hostname: zigbee2mqtt
    restart: unless-stopped
    depends_on:
      - mosquitto
    volumes:
      - D:/home-automation/zigbee2mqtt/data:/app/data
    ports:
      - 8485:8080
    environment:
      - TZ=${TZ}
    privileged: true
  mosquitto:
    image: eclipse-mosquitto:2.0.22
    container_name: mosquitto
    hostname: mosquitto
    restart: unless-stopped
    volumes:
      - D:/home-automation/mosquitto:/mosquitto
    ports:
      - 1883:1883
    environment:
      - TZ=${TZ}
  matter:
    image: ghcr.io/home-assistant-libs/python-matter-server:8.0.0
    container_name: matter
    hostname: matter
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    volumes:
      - D:/home-automation/matter:/data
    ports:
      - 5580:5580
    environment:
      - TZ=${TZ}
  openwakeword:
    image: homeassistant/amd64-addon-openwakeword:1.10.0
    container_name: openwakeword
    restart: unless-stopped
    entrypoint: python3
    command: >
      -m wyoming_openwakeword
      --uri 'tcp://0.0.0.0:10400'
      --preload-model 'ok_nabu'
      --custom-model-dir /share/openwakeword
    ports:
      - 10400:10400
    environment:
      - TZ=${TZ}
    volumes:
      - D:/openwakeword/data:/data
      - D:/openwakeword/custom-model-dir:/share/openwakeword
  piper:
    image: homeassistant/amd64-addon-piper:1.6.2
    container_name: piper
    restart: unless-stopped
    entrypoint: python3
    command: >
      -m wyoming_piper
      --piper '/usr/share/piper/piper'
      --uri 'tcp://0.0.0.0:10200'
      --length-scale "1"
      --noise-scale "0.667"
      --speaker "0"
      --voice "en_US-lessac-medium"
      --max-piper-procs "1"
      --data-dir /data
      --data-dir /share/piper
      --download-dir /data
    ports:
      - "10200:10200"
    volumes:
      - D:/piper/data:/data
  whisper:
    image: homeassistant/amd64-addon-whisper:2.6.0
    container_name: whisper
    restart: unless-stopped
    entrypoint: python3
    command: >
      -m wyoming_faster_whisper
      --uri tcp://0.0.0.0:10300
      --model small-int8
      --beam-size 1
      --language en
      --data-dir /data
      --download-dir /data
    ports:
      - "10300:10300"
    environment:
      - TZ=${TZ}
    volumes:
      - D:/whisper/data:/data
networks:
  homeassistant:
    driver: bridge