services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2025.7.2
    container_name: homeassistant
    hostname: homeassistant
    network_mode: host
    restart: unless-stopped
    privileged: true
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
  mosquitto:
    image: eclipse-mosquitto:2.0.22
    container_name: mqtt
    hostname: mqtt
    network_mode: host
    restart: unless-stopped
    privileged: true
    volumes:
      - ./mosquitto:/mosquitto
    environment:
      - TZ=${TZ}
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:2.5.1
    container_name: zigbee2mqtt
    hostname: zigbee2mqtt
    network_mode: host
    restart: unless-stopped
    privileged: true
    depends_on:
      - mosquitto
    volumes:
      - ./zigbee2mqtt/data:/app/data
    environment:
      - TZ=${TZ}
  matter:
    image: ghcr.io/home-assistant-libs/python-matter-server:8.0.0
    container_name: matter
    hostname: matter
    network_mode: host
    restart: unless-stopped
    privileged: true
    security_opt:
      - apparmor=unconfined
    volumes:
      - ./matter:/data
    environment:
      - TZ=${TZ}
  otbr:
    image: openthread/otbr:latest
    container_name: otbr
    hostname: otbr
    network_mode: host
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    environment:
      - RADIO_URL=spinel+hdlc+uart:///dev/ttyUSB0
      - FIREWALL=0
      - TZ=${TZ}
  openwakeword:
    image: homeassistant/amd64-addon-openwakeword:1.10.0
    container_name: openwakeword
    hostname: openwakeword
    network_mode: host
    restart: unless-stopped
    privileged: true
    entrypoint: python3
    command: >
      -m wyoming_openwakeword
      --uri 'tcp://0.0.0.0:10400'
      --preload-model 'ok_nabu'
      --custom-model-dir /share/openwakeword
    volumes:
      - ./openwakeword/data:/data
      - ./openwakeword/custom-model-dir:/share/openwakeword
    environment:
      - TZ=${TZ}
  piper:
    image: homeassistant/amd64-addon-piper:1.6.2
    container_name: piper
    hostname: piper
    network_mode: host
    restart: unless-stopped
    privileged: true
    entrypoint: python3
    command: >
      -m wyoming_piper
      --piper '/usr/share/piper/piper'
      --uri 'tcp://0.0.0.0:10200'
      --length-scale "1"
      --noise-scale "0.667"
      --speaker "0"
      --voice "en_US-lessac-medium"
      --max-piper-procs "1"
      --data-dir /data
      --data-dir /share/piper
      --download-dir /data
    volumes:
      - ./piper/data:/data
    environment:
      - TZ=${TZ}
  whisper:
    image: homeassistant/amd64-addon-whisper:2.6.0
    container_name: whisper
    hostname: whisper
    network_mode: host
    restart: unless-stopped
    privileged: true
    entrypoint: python3
    command: >
      -m wyoming_faster_whisper
      --uri tcp://0.0.0.0:10300
      --model small-int8
      --beam-size 1
      --language en
      --data-dir /data
      --download-dir /data
    volumes:
      - ./whisper/data:/data
    environment:
      - TZ=${TZ}