- alias: Toggle plug with button
  description: Toggle plug with button
  trigger:
   - platform: mqtt
     topic: zigbee2mqtt/Button/action
     payload: single
  action:
   - service: switch.toggle
     target:
       entity_id: switch.plug
  mode: single
